# base image
FROM openeuler/openeuler:22.03-lts

# MAINTAINER
MAINTAINER harvey

# yum install
RUN set -eux; \
    yum -y install git java tar cmake gperf sqlite-devel libffi-devel xz-devel zlib zlib-devel openssl-devel bzip2-devel ncurses-devel readline-devel libpcap-devel parted autoconf-archive chrpath gcc-c++ patch rpm-build flex autoconf automake m4 bison bc libtool gettext-devel createrepo_c git net-tools wget sudo hostname rpcgen texinfo python meson dosfstools mtools libmpc-devel gmp-devel ninja-build numactl-devel make

# gcc install
ARG tools_dir=/usr1/tools
ARG gcc_install_dir=/usr1/openeuler/gcc

# change dir to workdir and star install
WORKDIR ${tools_dir}
RUN wget https://repo.openeuler.org/openEuler-22.03-LTS/EPOL/main/x86_64/Packages/gcc-cross-1.0-0.oe2203.x86_64.rpm -P ${tools_dir}
RUN rpm2cpio ${tools_dir}/gcc-cross-1.0-0.oe2203.x86_64.rpm | cpio -id

# change dir to workdir and unpack
WORKDIR ${gcc_install_dir}
RUN tar -xf ${tools_dir}/tmp/openeuler_gcc_arm32le.tar.gz
RUN find ./openeuler_gcc_arm32le -type d | xargs chmod go+x
RUN chmod go+r ./openeuler_gcc_arm32le -R
RUN chmod -R 755 /usr1/openeuler/gcc/openeuler_gcc_arm32le/bin

RUN tar -xf ${tools_dir}/tmp/openeuler_gcc_arm64le.tar.gz
RUN find ./openeuler_gcc_arm64le -type d | xargs chmod go+x
RUN chmod go+r ./openeuler_gcc_arm64le -R
RUN chmod -R 755 /usr1/openeuler/gcc/openeuler_gcc_arm64le/bin
RUN find ./ | xargs chmod go+x


# clean install package
WORKDIR /usr1
RUN rm -rf tools

ARG VERSION=4.3
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG AGENT_WORKDIR=/home/${user}/agent

RUN curl --create-dirs -fsSLo /usr/share/jenkins/agent.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar \
    && chmod 755 /usr/share/jenkins \
    && chmod 644 /usr/share/jenkins/agent.jar \
    && ln -sf /usr/share/jenkins/agent.jar /usr/share/jenkins/slave.jar

RUN curl --create-dirs -fsSLo /usr/local/bin/jenkins-agent http://121.36.53.23/AdoptOpenJDK/jenkins-agent
#COPY jenkins-agent /usr/local/bin/jenkins-agent

RUN chmod a+rx /usr/local/bin/jenkins-agent \
     && ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave

RUN groupadd -g ${gid} ${group}
RUN useradd -c "Jenkins user" -d /home/${user} -u ${uid} -g ${gid} -m ${user}
RUN echo "${user} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers


USER ${user}
ENV AGENT_WORKDIR=${AGENT_WORKDIR}
RUN mkdir /home/${user}/.jenkins && mkdir -p ${AGENT_WORKDIR}

VOLUME /home/${user}/.jenkins
VOLUME ${AGENT_WORKDIR}
WORKDIR ${AGENT_WORKDIR}

# add build user
RUN sudo useradd -m openeuler


ENTRYPOINT ["jenkins-agent"]
